# This is the configuration used to check the rubocop source code.
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'Guardfile'
  TargetRubyVersion: 2.1
Metrics/LineLength:
  Max: 100
Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
